FORMAT: 1A
HOST: https://mydiary-challenge.herokuapp.com

# myDiary

Welcome to the myDiary API documentation. This is the API used by the myDiary web interface, so everything the web ui is able to do can also be accomplished via the API.
This API provides the connection for users to pen down their thoughts and feelings in an online Journal.


## Users [/api/v1/auth]

### User Signup  [POST]

Register a user

+ Request (application/json)

        {
                "username":"muche",
                "emill": "muche@email.com",
                "password": "password"
        }


+ Response 201 (application/json)

    + Headers

            Location: /signup

    + Body
    
            {
            "message": "Signup Successful",
            "id": 1,
            "user": {
            "username": "muche",
            "email": "muche@mail.com"
            },
            "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyOX0sImlhdCI6MTUxNTc1MzExNCwiZXhwIjoxNTE1NzU2NzE0fQ.sG-zNYLLSMTm6MtuhQ3XGZuTzsMqykeZSSzROkUvkNw",
            "status": "Successful",
            }

### User Login [POST]

Login a user

+ Request (application/json)

        {
            "username":"muche",
            "password": "password"

        }

+ Response 200 (application/json)

    + Headers

            Location: /login

    + Body

            {
            "message": "Login Successful!",
            "userDetails": {
            "username": "muche",
            "email": "muche@mail.com"
            },
            "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRpbnk4MyIsImVtYWlsIjoidWNoZWs3QGdtYWlsLmNvbSIsImlhdCI6MTUzMjk4MDgxNiwiZXhwIjoxNTMzMDY3MjE2fQ.3yyrpjNbyTtIKkWn_wl9pshODPpz10WN8j9j6IHTt1I"
            }

## Entries [/api/v1/entries]

### Create Entry [POST]

Add an entry

+ Request (application/json)

        {
          "title": "My first Journal"
          "mood": "Boring"  
          "entry": "Some text in my first journal"
        }

+ Response 201 (application/json)

    + Body
        
            {
            "message": "Entry Created Successfully",
            "newEntry": {
            "id": 7,
            "userId": 1,
            "title": "My first Journal",
            "mood": "Boring",
            "entry": "Some text in my first journal",
            "status": "Successful"
            }
            } 
            
### Modify an Entry [PUT]

Modify a diary entry

+ Request (application/json)
        
        {
          "title": "My first Journal"
          "mood": "Boring"  
          "entry": "Some text in my first journal"
        }

+ Response 200 (application/json)

    + Body
    
            {
            "entry": {
            "id": 2,
            "userid": 1,
            "title": "Last Summer Holiday",
            "mood": "Boring",
            "entry": "Some text in my first journal",
            "createdat": "2018-08-01T08:34:49.000Z"
            },
            "message": "Entry updated sucessfully",
            "status": "Successful"
            }

### Get Entries [GET]

Fetch all the entries for a user

+ Response 200 (application/json)

        [
            {
            "message": "Entries successfully retrieved from the database",
            "Entry": [
        {
            "id": 2,
            "userid": 1,
            "title": "About last",
            "mood": "party",
            "entry": "gftyn kjjnhiug uygfyufty gffdtrdtrs",
            "createdat": "2018-08-01T08:34:49.000Z"
        },
        {
            "id": 6,
            "userid": 1,
            "title": "Something in my journal",
            "mood": "Sleepy",
            "entry": "yugfwfjh; ;jh;iifji;oe iojioEWRUWQ ;OIHIOWHRiw ijioehIR IJHIORI ioheIORH KJBIUEHRu jiuehru KJBE;; EHOE",
            "createdat": "2018-07-01T10:35:41.000Z"
        },
        {
            "id": 7,
            "userid": 1,
            "title": "About next WEEK",
            "mood": "BORING",
            "entry": "gftyn kjjnhiug uygfyufty gffdtrdtrs",
            "createdat": "2018-08-01T14:00:35.000Z"
        }
        ],
        "status": "Successful"
        }
        
### Get One Entry [GET]

Fetch the details of an entry for a user

+ Response 200 (application/json)

        {
        "message": "Entry successfully retrieved from the database",
        "entry": {
        "id": 6,
        "userid": 1,
        "title": "Something in my journal",
        "mood": "Sleepy",
        "entry": "yugfwfjh; ;jh;iifji;oe iojioEWRUWQ ;OIHIOWHRiw ijioehIR IJHIORI ioheIORH KJBIUEHRu jiuehru KJBE;; EHOE",
        "createdat": "2018-07-01T10:35:41.000Z"
        },
        "status": "Successful"
        }

### Delete Entry [DELETE]

Delete a Diary Entry

+ Response 200 (application/json)

        {
        "message": "Entry successfully retrieved from the database",
        "entry": {
        "id": 6,
        "userid": 1,
        "title": "Something in my journal",
        "mood": "Sleepy",
        "entry": "yugfwfjh; ;jh;iifji;oe iojioEWRUWQ ;OIHIOWHRiw ijioehIR IJHIORI ioheIORH KJBIUEHRu jiuehru KJBE;; EHOE",
        "createdat": "2018-07-01T10:35:41.000Z"
        },
        "status": "Successful"
        }